language: go
go:
 - 1.x
 - tip

cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y haproxy

install: true

script:
  - go build ./...
  - ./hack/coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
