resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: appscodeci/github-pr-resource
    tag: latest

resources:
- name: voyager
  type: git
  source:
    uri: https://github.com/appscode/voyager
    branch: master

- name: pull-request
  type: pull-request
  source:
    owner: appscode
    repo: voyager
    label: ok-to-test
    access_token: ((access_token))

- name: creds
  type: s3
  source:
    bucket: appscode-ci
    access_key_id: ((s3-access-key))
    secret_access_key: ((s3-secret))
    versioned_file: appscode/voyager/voyager.zip

jobs:
- name: e2e-test-voyager
  plan:
  - get: voyager
    trigger: true
  - get: creds
    params:
      unpack: true
  - task: run-e2e-test
    file: voyager/hack/concourse/task.yml
    privileged: true
    params:
      TOKEN: ((digitaloceanToken))
      TEST_GCE_PROJECT: ((test_gce_project))
      TEST_ACME_USER_EMAIL: ((test_acme_user_email))
      TEST_DNS_DOMAINS: ((test_dns_domains))
      DOCKER_USER: ((docker_user))
      DOCKER_PASS: ((docker_pass))

- name: e2e-test-voyager-pr
  plan:
  - get: pull-request
    trigger: true
    version: every
  - get: creds
    params:
      unpack: true
  - put: pull-request
    params: {path: pull-request, status: pending}
  - task: run-e2e-test
    file: pull-request/hack/concourse/task.yml
    privileged: true
    input_mapping:
      voyager: pull-request
    params:
      TOKEN: ((digitaloceanToken))
      TEST_GCE_PROJECT: ((test_gce_project))
      TEST_ACME_USER_EMAIL: ((test_acme_user_email))
      TEST_DNS_DOMAINS: ((test_dns_domains))
      DOCKER_USER: ((docker_user))
      DOCKER_PASS: ((docker_pass))
    on_success:
      put: pull-request
      params: {path: pull-request, status: success}
    on_failure:
      put: pull-request
      params: {path: pull-request, status: failure}
