apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: voyager-operator
  name: voyager-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: voyager-operator
  template:
    metadata:
      labels:
        run: voyager-operator
    spec:
      containers:
      - name: voyager-operator
        args:
        - --cloud-provider=$CLOUD_PROVIDER
        - --cluster-name=$CLUSTER_NAME
        - --v=3
        image: appscode/voyager:1.5.4
        ports:
        - containerPort: 1234
          name: zero
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: voyager-operator
  name: voyager-operator
spec:
  ports:
  - name: zero
    port: 1234
    targetPort: zero
  selector:
    run: voyager-operator
