apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: voyager-operator
  name: voyager-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voyager-operator
  template:
    metadata:
      labels:
        app: voyager-operator
    spec:
      containers:
      - name: voyager-operator
        args:
        - run
        - --cloud-provider=$CLOUD_PROVIDER
        - --cloud-config=$CLOUD_CONFIG # ie. /etc/kubernetes/azure.json for azure
        - --v=3
        image: appscode/voyager:$TAG
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: /etc/kubernetes
            name: etc-kubernetes
      volumes:
        - hostPath:
            path: /etc/kubernetes
          name: etc-kubernetes
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: voyager-operator
  name: voyager-operator
  namespace: kube-system  
spec:
  ports:
  - name: http
    port: 56790
    targetPort: http
  selector:
    app: voyager-operator
