apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: appscode-voyager
  name: appscode-voyager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: appscode-voyager
  template:
    metadata:
      labels:
        run: appscode-voyager
    spec:
      containers:
      - name: appscode-voyager
        args:
        - --cloud-provider=$CLOUD_PROVIDER
        - --cluster-name=$CLUSTER_NAME
        - --v=3
        image: appscode/voyager:1.5.2
        ports:
        - containerPort: 1234
          name: zero
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: appscode-voyager
  name: appscode-voyager
spec:
  ports:
  - name: zero
    port: 1234
    targetPort: zero
  selector:
    run: appscode-voyager
