apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: voyager
  name: voyager-operator
  namespace: $VOYAGER_NAMESPACE
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: voyager
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: $VOYAGER_SERVICE_ACCOUNT
      imagePullSecrets: [$VOYAGER_IMAGE_PULL_SECRET]
      containers:
      - name: voyager
        args:
        - run
        - --v=3
        - --rbac=$VOYAGER_ENABLE_RBAC
        - --cloud-provider=$VOYAGER_CLOUD_PROVIDER
        - --cloud-config=$VOYAGER_CLOUD_CONFIG # ie. /etc/kubernetes/azure.json for azure
        - --ingress-class=$VOYAGER_INGRESS_CLASS
        - --restrict-to-operator-namespace=$VOYAGER_RESTRICT_TO_NAMESPACE
        - --docker-registry=$VOYAGER_DOCKER_REGISTRY
        image: $VOYAGER_DOCKER_REGISTRY/voyager:5.0.0-rc.11
        ports:
        - containerPort: 56790
          name: ops
          protocol: TCP
        - containerPort: 56791
          name: acme
          protocol: TCP
        volumeMounts:
          - mountPath: /etc/kubernetes
            name: cloudconfig
            readOnly: true
      volumes:
        - hostPath:
            path: /etc/kubernetes
          name: cloudconfig
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: voyager
  name: voyager-operator
  namespace: $VOYAGER_NAMESPACE
spec:
  ports:
  - name: ops
    port: 56790
    targetPort: ops
  - name: acme
    port: 56791
    targetPort: acme
  selector:
    app: voyager
