/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	voyagerv1beta1 "voyagermesh.dev/apimachinery/apis/voyager/v1beta1"
	scheme "voyagermesh.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IngressesGetter has a method to return a IngressInterface.
// A group's client should implement this interface.
type IngressesGetter interface {
	Ingresses(namespace string) IngressInterface
}

// IngressInterface has methods to work with Ingress resources.
type IngressInterface interface {
	Create(ctx context.Context, ingress *voyagerv1beta1.Ingress, opts v1.CreateOptions) (*voyagerv1beta1.Ingress, error)
	Update(ctx context.Context, ingress *voyagerv1beta1.Ingress, opts v1.UpdateOptions) (*voyagerv1beta1.Ingress, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, ingress *voyagerv1beta1.Ingress, opts v1.UpdateOptions) (*voyagerv1beta1.Ingress, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*voyagerv1beta1.Ingress, error)
	List(ctx context.Context, opts v1.ListOptions) (*voyagerv1beta1.IngressList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *voyagerv1beta1.Ingress, err error)
	IngressExpansion
}

// ingresses implements IngressInterface
type ingresses struct {
	*gentype.ClientWithList[*voyagerv1beta1.Ingress, *voyagerv1beta1.IngressList]
}

// newIngresses returns a Ingresses
func newIngresses(c *VoyagerV1beta1Client, namespace string) *ingresses {
	return &ingresses{
		gentype.NewClientWithList[*voyagerv1beta1.Ingress, *voyagerv1beta1.IngressList](
			"ingresses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *voyagerv1beta1.Ingress { return &voyagerv1beta1.Ingress{} },
			func() *voyagerv1beta1.IngressList { return &voyagerv1beta1.IngressList{} },
		),
	}
}
