apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: certificates.voyager.appscode.com
  labels:
    app: voyager
spec:
  group: voyager.appscode.com
  names:
    kind: Certificate
    listKind: CertificateList
    plural: certificates
    shortNames:
    - cert
    singular: certificate
  scope: Namespaced
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingresses.voyager.appscode.com
  labels:
    app: voyager
spec:
  group: voyager.appscode.com
  names:
    kind: Ingress
    listKind: IngressList
    plural: ingresses
    shortNames:
    - ing
    singular: ingress
  scope: Namespaced
  version: v1beta1
