/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s.io/api/core/v1"
)

// CoordinatorSpecApplyConfiguration represents an declarative configuration of the CoordinatorSpec type for use
// with apply.
type CoordinatorSpecApplyConfiguration struct {
	Resources       *v1.ResourceRequirements `json:"resources,omitempty"`
	SecurityContext *v1.SecurityContext      `json:"securityContext,omitempty"`
}

// CoordinatorSpecApplyConfiguration constructs an declarative configuration of the CoordinatorSpec type for use with
// apply.
func CoordinatorSpec() *CoordinatorSpecApplyConfiguration {
	return &CoordinatorSpecApplyConfiguration{}
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *CoordinatorSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *CoordinatorSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *CoordinatorSpecApplyConfiguration) WithSecurityContext(value v1.SecurityContext) *CoordinatorSpecApplyConfiguration {
	b.SecurityContext = &value
	return b
}
