apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: "{{ template "name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: ops
    port: 56790
    targetPort: ops
  - name: acme
    port: 56791
    targetPort: acme
  selector:
    app: "{{ template "name" . }}"
    release: "{{ .Release.Name }}"
