apiVersion: v1
kind: Service
metadata:
  labels:
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: web
  selector:
    app: "{{ template "fullname" . }}"
