apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kiteci-azure-dns
  namespace: default
spec:
  secretName: kiteci-azure-dns-tls
  issuerRef:
    name: letsencrypt-staging-dns
  dnsNames:
    - kiteci-azure-dns.appscode.info