/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// BasicAuthApplyConfiguration represents an declarative configuration of the BasicAuth type for use
// with apply.
type BasicAuthApplyConfiguration struct {
	SecretName *string `json:"secretName,omitempty"`
	Realm      *string `json:"realm,omitempty"`
}

// BasicAuthApplyConfiguration constructs an declarative configuration of the BasicAuth type for use with
// apply.
func BasicAuth() *BasicAuthApplyConfiguration {
	return &BasicAuthApplyConfiguration{}
}

// WithSecretName sets the SecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretName field is set to the value of the last call.
func (b *BasicAuthApplyConfiguration) WithSecretName(value string) *BasicAuthApplyConfiguration {
	b.SecretName = &value
	return b
}

// WithRealm sets the Realm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Realm field is set to the value of the last call.
func (b *BasicAuthApplyConfiguration) WithRealm(value string) *BasicAuthApplyConfiguration {
	b.Realm = &value
	return b
}
