/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// HTTPIngressBackendApplyConfiguration represents an declarative configuration of the HTTPIngressBackend type for use
// with apply.
type HTTPIngressBackendApplyConfiguration struct {
	IngressBackendApplyConfiguration `json:",omitempty,inline"`
	RewriteRules                     []string `json:"rewriteRules,omitempty"`
	HeaderRules                      []string `json:"headerRules,omitempty"`
}

// HTTPIngressBackendApplyConfiguration constructs an declarative configuration of the HTTPIngressBackend type for use with
// apply.
func HTTPIngressBackend() *HTTPIngressBackendApplyConfiguration {
	return &HTTPIngressBackendApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HTTPIngressBackendApplyConfiguration) WithName(value string) *HTTPIngressBackendApplyConfiguration {
	b.Name = &value
	return b
}

// WithHostNames adds the given value to the HostNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the HostNames field.
func (b *HTTPIngressBackendApplyConfiguration) WithHostNames(values ...string) *HTTPIngressBackendApplyConfiguration {
	for i := range values {
		b.HostNames = append(b.HostNames, values[i])
	}
	return b
}

// WithServiceName sets the ServiceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceName field is set to the value of the last call.
func (b *HTTPIngressBackendApplyConfiguration) WithServiceName(value string) *HTTPIngressBackendApplyConfiguration {
	b.ServiceName = &value
	return b
}

// WithServicePort sets the ServicePort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServicePort field is set to the value of the last call.
func (b *HTTPIngressBackendApplyConfiguration) WithServicePort(value intstr.IntOrString) *HTTPIngressBackendApplyConfiguration {
	b.ServicePort = &value
	return b
}

// WithBackendRules adds the given value to the BackendRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BackendRules field.
func (b *HTTPIngressBackendApplyConfiguration) WithBackendRules(values ...string) *HTTPIngressBackendApplyConfiguration {
	for i := range values {
		b.BackendRules = append(b.BackendRules, values[i])
	}
	return b
}

// WithALPN adds the given value to the ALPN field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ALPN field.
func (b *HTTPIngressBackendApplyConfiguration) WithALPN(values ...string) *HTTPIngressBackendApplyConfiguration {
	for i := range values {
		b.ALPN = append(b.ALPN, values[i])
	}
	return b
}

// WithProto sets the Proto field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Proto field is set to the value of the last call.
func (b *HTTPIngressBackendApplyConfiguration) WithProto(value string) *HTTPIngressBackendApplyConfiguration {
	b.Proto = &value
	return b
}

// WithLoadBalanceOn sets the LoadBalanceOn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalanceOn field is set to the value of the last call.
func (b *HTTPIngressBackendApplyConfiguration) WithLoadBalanceOn(value string) *HTTPIngressBackendApplyConfiguration {
	b.LoadBalanceOn = &value
	return b
}

// WithRewriteRules adds the given value to the RewriteRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RewriteRules field.
func (b *HTTPIngressBackendApplyConfiguration) WithRewriteRules(values ...string) *HTTPIngressBackendApplyConfiguration {
	for i := range values {
		b.RewriteRules = append(b.RewriteRules, values[i])
	}
	return b
}

// WithHeaderRules adds the given value to the HeaderRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the HeaderRules field.
func (b *HTTPIngressBackendApplyConfiguration) WithHeaderRules(values ...string) *HTTPIngressBackendApplyConfiguration {
	for i := range values {
		b.HeaderRules = append(b.HeaderRules, values[i])
	}
	return b
}
