/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// LocalTypedReferenceApplyConfiguration represents an declarative configuration of the LocalTypedReference type for use
// with apply.
type LocalTypedReferenceApplyConfiguration struct {
	Kind       *string `json:"kind,omitempty"`
	Name       *string `json:"name,omitempty"`
	APIVersion *string `json:"apiVersion,omitempty"`
}

// LocalTypedReferenceApplyConfiguration constructs an declarative configuration of the LocalTypedReference type for use with
// apply.
func LocalTypedReference() *LocalTypedReferenceApplyConfiguration {
	return &LocalTypedReferenceApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *LocalTypedReferenceApplyConfiguration) WithKind(value string) *LocalTypedReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LocalTypedReferenceApplyConfiguration) WithName(value string) *LocalTypedReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *LocalTypedReferenceApplyConfiguration) WithAPIVersion(value string) *LocalTypedReferenceApplyConfiguration {
	b.APIVersion = &value
	return b
}
