apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-cleaner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "voyager.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 120
  template:
    spec:
      serviceAccountName: {{ include "voyager.serviceAccountName" . }}
      containers:
      - name: busybox
        image: {{ .Values.cleaner.registry }}/{{ .Values.cleaner.repository }}:{{ .Values.cleaner.tag }}
        command:
          - sh
          - -c
          - "sleep 2; \
          kubectl delete validatingwebhookconfigurations admission.voyager.appscode.com || true; \
          kubectl delete apiservice v1alpha1.admission.voyager.appscode.com || true"
        imagePullPolicy: {{ .Values.imagePullPolicy  }}
      restartPolicy: Never
