{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- $criticalAddon := and .Values.criticalAddon (or (eq .Release.Namespace "kube-system") (and (ge $major 1) (ge $minor 17))) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voyager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "voyager.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "voyager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "voyager.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/apiregistration.yaml: {{ include (print $.Template.BasePath "/apiregistration.yaml") . | sha256sum }}
      {{- if $criticalAddon }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "voyager.serviceAccountName" . }}
      containers:
      - name: voyager
        securityContext:
          {{- toYaml .Values.voyager.securityContext | nindent 10 }}
        image: {{ .Values.voyager.registry }}/{{ .Values.voyager.repository }}:{{ .Values.voyager.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy  }}
        args:
        - run
        - --cloud-provider={{ .Values.cloudProvider }}
        - --cloud-config={{ .Values.cloudConfig }}
        - --v={{ .Values.logLevel }}
        - --ingress-class={{ .Values.ingressClass }}
        - --operator-service={{ include "voyager.fullname" . }}
        - --docker-registry={{ .Values.haproxy.registry }}
        - --haproxy-image-tag={{ .Values.haproxy.tag }}
        - --haproxy-image-repository={{ .Values.haproxy.repository }}
        - --exporter-image-tag={{ .Values.voyager.tag }}
        - --exporter-image-repository={{ .Values.voyager.repository }}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --enable-validating-webhook={{ .Values.apiserver.enableValidatingWebhook }}
        - --bypass-validating-webhook-xray={{ .Values.apiserver.bypassValidatingWebhookXray }}
        - --use-kubeapiserver-fqdn-for-aks={{ .Values.apiserver.useKubeapiserverFqdnForAks }}
        - --enable-analytics={{ .Values.enableAnalytics }}
      {{- with .Values.restrictToOperatorNamespace }}
        - --restrict-to-operator-namespace={{ . }}
      {{- end }}
      {{- if .Values.templates.cfgmap }}
        - --custom-templates=/srv/voyager/custom/*.cfg
      {{- end }}
        ports:
        - containerPort: 8443
        - containerPort: 56791
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      {{- if .Values.apiserver.healthcheck.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
      {{- end }}
        resources:
          {{- toYaml .Values.voyager.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
      {{- if .Values.persistence.enabled }}
        - mountPath: {{ dir .Values.cloudConfig | quote }}
          name: cloudconfig
          readOnly: true
      {{- end }}
      {{- if .Values.templates.cfgmap }}
        - mountPath: /srv/voyager/custom
          name: templates
          readOnly: true
      {{- end }}
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ include "voyager.fullname" . }}-apiserver-cert
    {{- if .Values.persistence.enabled }}
      - hostPath:
          path: {{ .Values.persistence.hostPath | quote }}
        name: cloudconfig
    {{- end }}
    {{- if .Values.templates.cfgmap }}
      - configMap:
          name: {{ .Values.templates.cfgmap }}
        name: templates
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if or .Values.tolerations $criticalAddon }}
      tolerations:
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $criticalAddon }}
        - key: CriticalAddonsOnly
          operator: Exists
      {{- end -}}
    {{- end -}}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $criticalAddon }}
      priorityClassName: system-cluster-critical
    {{- end -}}
