{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "voyager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "voyager.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
imagePullSecrets:
  {{- range $x := .Values.imagePullSecrets }}
  - name: "{{ $x }}"
  {{- end }}
{{ end }}
