apiVersion: v1
kind: Service
metadata:
  name: {{ include "voyager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "voyager.labels" . | nindent 4 }}
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: admission
    port: 443
    targetPort: 8443
  # Port used to respond to Let's Encrypt HTTP challenges
  - name: acme
    port: 56791
    targetPort: 56791
  selector:
    {{- include "voyager.selectorLabels" . | nindent 4 }}
