apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: kitecicom
  namespace: default
spec:
  domains:
  - kiteci.com
  - www.kiteci.com
  acmeUserSecretName: acme-account
  challengeProvider:
    dns:
      provider: gce
      credentialSecretName: voyager-gce
  storage:
    secret:
      name: cert-kitecipro
