name: Release

on:
  push:
    tags:
      - '*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Print version info
      id: semver
      run: |
        make version

    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Prepare build host
      run: |
        ./hack/builddeps.sh

    - name: Build
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        USERNAME: 1gtm
        APPSCODE_ENV: prod
      run: |
        docker login --username ${USERNAME} --password ${DOCKER_TOKEN}
        make release
        ./hack/release.sh

  helm:
    name: Helm
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Clone charts repository
      env:
        GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
      run: |
        cd $HOME
        git clone https://1gtm:${GITHUB_TOKEN}@github.com/appscode/charts.git
        cd charts
        git config user.name "1gtm"
        git config user.email "1gtm@appscode.com"

    - name: Package
      run: |
        echo "install helm 3"
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        echo "package chart"
        helm package charts/voyager
        mv voyager-*.tgz $HOME/charts/stable/voyager

    - name: Create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
      run: |
        export PR_BRANCH=${GITHUB_REPOSITORY}/${GITHUB_RUN_ID}
        echo $PR_BRANCH
        cd $HOME/charts
        git checkout -b $PR_BRANCH
        git commit -a -s -m "Push voyager chart for $GITHUB_REF"
        git push origin $PR_BRANCH -f
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pull-request -m "Push voyager chart for $GITHUB_REF"
